# cspell init --stdout > .cspell.config.yaml で出力したものをカスタマイズ

# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

# The version of the configuration file format.
version: "0.2"
# The locale to use when spell checking. (e.g., en, en-GB, de-DE
language: en

# ノイズ源を除外
ignorePaths:
  - "**/node_modules/**"
  - "**/.devbox/**"
  - "**/.devcontainer/.state/**"
  - "**/*.svg"
  - "**/*.drawio"
  - ".typos.toml"

# 単語登録（少量なら)
words:
  - "hoge"
  - "fuga"
  # .claude/settings.json
  - "mcpjson"
  # .codex/config.toml
  - "xhigh"
  # .devcontainer/devcontainer.json
  - "moby"
  - "emeraldwalk"
  - "runonsave"
  - "tamasfe"
  - "jetpack"
  - "worktree"
  # .devcontainer/Dockerfile
  - "pipefail"
  - "nopasswd"
  # images/DEVELOPMENT.md
  - "aazw"
  - "nixhub"
  # images/*/devbox_install.sh
  - "devbox"
  - "grealpath"
  - "jetpackio"
  # images/*/devbox.json
  - "nixpkgs"
  - "certdata"
  - "nslookup"
  - "sqruff"
  - "taplo"
  - "tombi"
  - "rumdl"
  - "mmdc"
  - "rustc"
  - "objdump"
  - "libdispatch"
  - "Werror"
  - "Wsign"
  - "nixos"
  - "swiftc"
  - "swiftpm"
  - "corelibs"
  - "docc"
  - "staticcheck"
  # - images/*/.devcontainer/Dockerfile
  - "shellenv"
  - "cainfo"
  - "vscjava"
  - "dbaeumer"
  - "bradlc"
  - "isort"
  - "charliermarsh"
  - "venv"
  - "swiftlang"
  - "libc"
  - "stdlib"
  # tools/merge_devbox/jsonc2json.js
  - "schemafile"
  # Taskfile.yml
  - "taskfile"
  - "treefmt"
  - "commitlint"
  # .treefmt.toml
  - "dockerfmt"
  - "githubactions"
  - "zizmor"
  - "jsonschema"
  - "shellcheck"
  - "shfmt"
  # trivy.yaml
  - "aquasec"
  - "aquasecurity"
  - "ignorefile"
  - "confidencelevel"
  - "pkgs"
  - "terraformplan"
  - "rego"
  - "rekor"
  # .github/workflows/*.yaml
  - "dockerfiles"
  - "dorny"
  - "hostedtoolcache"
  - "graalvm"
  - "ghcup"
  - "buildx"
  - "dockerhub"
  - "opencontainers"
  - "tonumber"
  - "shopt"
  - "nullglob"
  - "imagetools"
  - "jetify"
  - "unmatch"
  # .github/zizmor.yml
  - "basenames"
  # .hadolint.yaml
  - "codeclimate"
  - "codacy"
  # .gitignore
  - "dotenv"
  - "fseventsd"
  - "timemachine"
  - "donotpresent"
  - "apdisk"
  - "pids"
  - "jscoverage"
  - "wscript"
  - "jspm"
  - "eslintcache"
  - "stylelintcache"
  - "microbundle"
  - "nuxt"
  - "vuepress"
  - "encryptable"
  - "ehthumbs"
  - "stackdump"
  - "esktop"
  - "msix"
  # .cspell.config.yaml
  - "mxfile"
  - "xlink"
  - "katex"
  - "rela"
  - "encrypter"
  - "ffor"
  - "wronly"
  - "arange"
  - "bitbake"
  - "countr"
  - "egals"
  - "egal"
  - "flate"
  - "modul"
  - "ratatui"
  - "stap"
  - "usig"
  - "vimscript"
  - "windo"
